package com.xuke.springcloud.entities;

public class Payment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.id
     *
     * @mbggenerated Wed Jun 17 21:13:09 GMT+08:00 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.seriler
     *
     * @mbggenerated Wed Jun 17 21:13:09 GMT+08:00 2020
     */
    private String seriler;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.id
     *
     * @return the value of payment.id
     *
     * @mbggenerated Wed Jun 17 21:13:09 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.id
     *
     * @param id the value for payment.id
     *
     * @mbggenerated Wed Jun 17 21:13:09 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.seriler
     *
     * @return the value of payment.seriler
     *
     * @mbggenerated Wed Jun 17 21:13:09 GMT+08:00 2020
     */
    public String getSeriler() {
        return seriler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.seriler
     *
     * @param seriler the value for payment.seriler
     *
     * @mbggenerated Wed Jun 17 21:13:09 GMT+08:00 2020
     */
    public void setSeriler(String seriler) {
        this.seriler = seriler == null ? null : seriler.trim();
    }
}