server:
  port: 8006

spring:
  application:
    name: cloud-payment-service-hystrix

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka